spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb

jwt:
  secret:
    key: RJAJDROAODKWKAORODKA123WJJADJ24WAKDK2WROAOSDMRKSOCOSKWMRLSPW+2WEQRASCC+QQSADW@DDGLJKJ
